---
language: bash
services: docker

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

before_script:
  - export IMAGE=luislavena/yaml-combiner:latest

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build -t "$IMAGE" .
      IMAGE=$IMAGE bats tests/
    )

after_script:
  - docker images

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
